# ---------------------------
# DATASOURCE
# ---------------------------
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/lirium}
spring.datasource.username=${DB_USER_NAME:postgres}
spring.datasource.password=${DB_PASSWORD:tu_password}
spring.datasource.driver-class-name=org.postgresql.Driver

# ---------------------------
# JWT
# ---------------------------
app.jwt.secret=${JWT_SECRET:una-clave-dev-lirium-muy-larga}

# ---------------------------
# GOOGLE OAUTH
# ---------------------------
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID:}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET:}
spring.security.oauth2.client.registration.google.scope=email,profile