# ---------------------------
# CONFIGURACIÓN DEL SERVIDOR
# ---------------------------
server.port=8080

# ---------------------------
# CONFIG H2 (CONSOLA)
# ---------------------------
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ---------------------------
# CONFIGURACIÓN JPA / HIBERNATE
# ---------------------------
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# Dialecto recomendado para H2
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# ---------------------------
# DATA SOURCE (H2 en memoria)
# ---------------------------
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driverClassName=org.h2.Driver

spring.profiles.active=dev