# ---------------------------
# CONFIGURACION DEL SERVIDOR
# ---------------------------
server.port=8080

# ---------------------------
# CONFIG H2 (CONSOLA)
# ---------------------------
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# ---------------------------
# CONFIGURACION JPA / HIBERNATE
# ---------------------------
spring.jpa.show-sql=true
# spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
hibernate.hbm2ddl.auto=create
#spring.jpa.properties.javax.persistence.schema-generation.scripts.action=create

# Dialecto recomendado para H2
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# ---------------------------
# DATA SOURCE (H2 en memoria)
# ---------------------------
#spring.datasource.url=jdbc:h2:file:./data/testdb;AUTO_SERVER=TRUE
#spring.datasource.username=sa
#spring.datasource.password=
#spring.datasource.driverClassName=org.h2.Driver

# ---------------------------
# DATA SOURCE (PostgreSql)
# ---------------------------
spring.datasource.url=jdbc:postgresql://localhost:5432/lirium
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

#spring.jpa.hibernate.ddl-auto=create
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# spring.profiles.active=dev

app.jwt.secret=${JWT_SECRET:esta-es-una-clave-secreta-muy-larga-y-segura-para-desarrollo-32-chars}
app.jwt.expiration=900000
app.jwt.refresh-expiration=604800000

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile

# momntatneo
spring.jpa.hibernate.ddl-auto=none

spring.jpa.properties.javax.persistence.schema-generation.database.action=none
spring.jpa.properties.javax.persistence.schema-generation.scripts.action=create

spring.jpa.properties.javax.persistence.schema-generation.scripts.create-target=target/schema.sql
spring.jpa.properties.javax.persistence.schema-generation.create-source=metadata